condense_wildcard_suffixes=true
format_macro_matchers=true
group_imports="StdExternalCrate"
imports_granularity="Module"
max_width=80
normalize_comments=true
reorder_impl_items=true
style_edition="2024"
use_field_init_shorthand=true
use_try_shorthand=true
wrap_comments=true
